### ISSUE TITLE
sbtPlugin does not run when when using docker plugin

### ISSUE THREAD

**Issue by kbedel** [iheartradio/play-swagger#114]
When I use the docker sbt plugin to create a docker image, it does not create the output swagger.json file.

```
>docker:stage
[info] Loading project definition from D:\workspace\myProject\project
[info] Set current project to myProject (in build file:/D:/workspace/myProject/)
[info] Packaging D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0-sources.jar ...
[info] Wrote D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0.pom
[info] Updating {file:/D:/workspace/myProject/}myProject...
[info] Resolving com.typesafe.play#play-netty-utils;2.5.4 ...
[info] Done packaging.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 7 Scala sources and 2 Java sources to D:\workspace\myProject\target\scala-2.11\classes...
[info] Packaging D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0.jar ...
[info] Done packaging.
[info] Packaging D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0-sans-externalized.jar ...
[info] Done packaging.
[success] Total time: 28 s, completed Aug 31, 2016 5:18:15 PM
```

If I use the regular stage command, I see the line reporting it is generating the output:

```
>stage
[info] Loading project definition from D:\workspace\myProject\project
[info] Set current project to myProject (in build file:/D:/workspace/myProject/)
[info] Compiling 4 Scala sources and 1 Java source to D:\workspace\myProject\target\scala-2.11\classes...
[info] Running com.iheart.playSwagger.SwaggerSpecRunner D:\workspace\myProject\target\swagger\swagger.json routes mynamespace
[info] Packaging D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0-web-assets.jar ...
[info] Done packaging.
[info] Packaging D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0.jar ...
[info] Wrote D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0.pom
[info] Done packaging.
[info] Packaging D:\workspace\myProject\target\scala-2.11\myProject_2.11-1.0-sans-externalized.jar ...
[info] Done packaging.
[success] Total time: 12 s, completed Aug 31, 2016 5:18:42 PM
```

**Comment by kailuowang** [comment]
I wonder if change the attaching task from `stage` to `package` would solve this problem? 

Here: https://github.com/iheartradio/play-swagger/blob/master/sbtPlugin/src/main/scala/com/iheart/sbtPlaySwagger/SwaggerPlugin.scala#L45

**Comment by kbedel** [comment]
I'm not very familiar with sbt plugins, but looking at the source of the sbt-native-packager docker plugin, I don't think it will. It looks like this directly stages the files without using any of the basic tasks:

https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L131

**Comment by mosche** [comment]
Hey guys,
it's a bit unfortunate the way the docker plugin redefines stage. 
However, the solution is pretty simple. Just add:
```
(stage in Docker) <<= (stage in Docker).dependsOn(swagger)
```
This could be added into the plugin, but that would make it dependent on the DockerPlugin ...
Cheers, M

**Comment by chafikhnini** [comment]
Hi guys,

I've just had the same problem with `activator universal:packageZipTarball`. Since only `packageBin` is referenced in the [plugin configuration](https://github.com/iheartradio/play-swagger/blob/master/sbtPlugin/src/main/scala/com/iheart/sbtPlaySwagger/SwaggerPlugin.scala#L44) it does not generate the `swagger.json`.

Fixed it by adding :

    (packageZipTarball in Universal) <<= (packageZipTarball in Universal).dependsOn(swagger)

to my `build.sbt`.

Maybe there is a way to handle all `universal` tasks in the plugin configuration ?

**Comment by mosche** [comment]
Hi,
if feels clumsy, but I don't know a better way than just adding all of the universal packagers to the projectSettings in the plugin.
```
Seq(packageBin, packageOsxDmg, packageZipTarball, packageXzTarball).map( universalPackage ⇒
  universalPackage in Universal <<= (universalPackage in Universal).dependsOn(swagger)
)
```

**Comment by longliveenduro** [comment]
@mosche Thanks Moritz. '<<=' is removed in sbt 1.x and unfortunately the suggested replacement does not work for me
```
Seq(packageBin, packageOsxDmg, packageZipTarball, packageXzTarball).map( universalPackage ⇒
  universalPackage in Universal := (universalPackage in Universal).dependsOn(swagger).value
)
```

**Comment by mosche** [comment]
@longliveenduro Hey Chris, how are you trying to package your app?

**Comment by longliveenduro** [comment]
I do use `sbt universal:packageZipTarball` with sbt version 1.1.1 and play swagger 0.7.4

**Comment by mosche** [comment]
Sorry Chris, I currently don't have such an example handy. 
Do you get an error, or does it just not trigger the swagger task?

If the latter is the case, are you defining the settings in a plugin or in your build.sbt? If it's a plugin, you might just need to depend on UniversalPlugin to force the right initialization order of your settings.

Otherwise happy to have a look if you push some code.

**Comment by longliveenduro** [comment]
@mosche Hi Moritz. The swagger task gets executed, so the swagger.json is created and is in target/swagger. The only thing that does not work is that it ends up in the final tarball. Seems there is somehow the attachment of the resource missing. As I package it in a docker image I could easily make a workaround by copying it to the image manually. So that works for me with that workaround. Thanks, Moritz!

**Comment by mosche** [comment]
@longliveenduro This is the line that should do the job, but apparently not in your case :/
https://github.com/iheartradio/play-swagger/blob/master/sbtPlugin/src/main/scala/com/iheart/sbtPlaySwagger/SwaggerPlugin.scala#L51

You could give it a try using `mappings in Universal` instead to add the same mapping as linked above.

**Comment by longliveenduro** [comment]
@mosche Thanks Moritz. Adding 
`mappings in Universal += (swaggerTarget.value / swaggerFileName.value) → s"public/${swaggerFileName.value}" //include it in the unmanagedResourceDirectories in Assets doesn't automatically include it package`
fixes the problem. The current mapping in the plugin only works for the zip file and not the tarball. Thanks mate!

**Comment by Ozzee** [comment]
For anybody trying to use the `docker:stage` command in the Play Framework. We had this same issue and solved it by adding
```
stage in Docker := (stage in Docker).dependsOn(swagger).value
```
to our `build.sbt`. Maybe someone finds this useful :)

**Comment by CornelZ** [comment]
Hi, 

I tried everything you guys recommended. Nothing seems to work. I can't get rid of the error
`SwaggerSpecGenerator$MissingBaseSpecException$: Missing a swagger.yml or swagger.json to provide base swagger spec`
when i run `docker:stage` task

I have a Java Multi-project setup like this
play framework 2.8.8
sbt 1.3.13
scala 2.13.6
sbt-play-swagger 0.10.6-PLAY2.8

when I run `swagger` command everything runs fine.
command `docker:stage` fails with MissingBaseSpecException

I don't know what to try anymore. 
I tried what @Ozzee recommended: no change
I tried putting the swagger.yml base file all around the projects folder: nothing.
Tried to add mappings of folders .. nothing. 

Same error, no matter what I do.

The plugin does not say where it searches for the file. I can't even debug this.

Can you please spam me with some ideas with what can I try, or how does this work internally. 
What does `docker:stage` do, so that `swagger` can't see the base swagger spec file ?

Are there any other options ? 
I tried to remove swagger from docker:stage, can't do it.

Thanks in advance
