### ISSUE TITLE
Correction: Specifying a Spec that bumps up against another comment doesnt get processed

### ISSUE THREAD

**Issue by narayanjr** [iheartradio/play-swagger#138]
```
####################
##     Test       ##
####################
###
#  summary: Adds a Business Sector
###
POST 	/business_sectors 	controllers.admin.BusinessSectors.createBusinessSector()
```

This fails to generate anything besides

```
"/api/admin/v1/business_sectors": {
      "post": {
        "tags": [
          "admin"
        ]
      }
    },
```

Adding in a blank line between the end of the comment and the spec ### makes it work.

```
####################
##     Test       ##
####################

###
#  summary: Adds a Business Sector
###
POST 	/business_sectors 	controllers.admin.BusinessSectors.createBusinessSector()
```

**Comment by stefnotch** [comment]
I think, this issue happens because the code that extracts the spec is rather simplistic:
[First of all, it checks if there is a NoDocs comment](https://github.com/iheartradio/play-swagger/blob/master/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L305)

[If it is not a NoDocs comment, play-swagger tries to parse the comment.](https://github.com/iheartradio/play-swagger/blob/master/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L329)
```
   def tryParseYaml(comment: String): Option[JsObject] = {
      val pattern = "^\\w+:".r
      pattern.findFirstIn(comment).map(_ ⇒ parseYaml[JsObject](comment))
    }

    def tryParseJson(comment: String): Option[JsObject] = {
      if (comment.startsWith("{"))
        Some(Json.parse(comment).as[JsObject])
      else None
    }
```
As you can see, it only checks if the first line is a valid JSON or a valid YAML comment.

The case where comments are separated by a blank line works because those are 2 different comments and the bottom comment is a valid YAML comment.
