### ISSUE TITLE
Unresolved dependency for scala 2.11 and play 2.6

### ISSUE THREAD

**Issue by samupra** [iheartradio/play-swagger#173]
I can see here that : https://jcenter.bintray.com/com/iheart/play-swagger_2.11/

Nothing exists for Play 2.6, but it exists for 2.12, can you please check?

**Comment by pocman** [comment]
Yes, I have the same issue.
I add to disable swagger when migrating to play 2.6...

**Comment by pocman** [comment]
Same here, I had to remove the swagger plugin when migrating to play 2.6

**Comment by kailuowang** [comment]
Right now the play 2.6 branch doesn't cross build between 2.11 and 2.12. I myself doesn't have time to address this issue (cross building is a bit complicated because we have a sbt-plugin as a sub-module). Anyone interested in adding crossbuild on the 2.6 branch will be really appreciated. In the meantime,  there is an ongoing effort to cross build the sbt plugin between sbt 1.0 and sbt 0.13.x by @wlk see https://github.com/iheartradio/play-swagger/issues/177

**Comment by samupra** [comment]
Okay, working on it!

**Comment by pocman** [comment]
@samupra do you have any update on this issue ?

**Comment by samupra** [comment]
@pocman not at the moment sorry !

**Comment by samupra** [comment]
Anyone can take this up if they wish so.

**Comment by mikeumus** [comment]
Putting the path in `~/.sbt/repositories` that had a version for Scala 2.10 that worked with my sbt 0.13 worked for me:

```
[repositories]
local
iheart-sbt-plugin-releases: https://dl.bintray.com/iheartradio/sbt-plugins, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier] ).[ext]
iheart-play-swagger_2.11-releases: https://jcenter.bintray.com
```

and the `jcenter` version for `sbt publishLocal`
