### ISSUE TITLE
How can I add a description to a schema/model parameter?

### ISSUE THREAD

**Issue by EdgarDorausch** [iheartradio/play-swagger#205]
Let us say `case class Category(id: Option[Int], name: String, parentId: Int) { ... }` is our model. How can I add a description to (for example) parentId?

**Comment by sohoffice** [comment]
I've tweaked the play-swagger plugin so that it accepts a java properties file to supply the descriptions. A second plugin [docExtract](https://github.com/sohoffice/docExtract) was added to extract scaladoc from your scala source files.

docExtract currently only works on scala files (it's implemented as a doclet of scaladoc) and it only supports sbt 1.0.

I can submit a pull request if you find the above useful.

**Comment by Javakky-pxv** [comment]
@EdgarDorausch  @sohoffice 
The extraction of Scaladoc has been supported. ( #499  )
