### ISSUE TITLE
Can't read from server. It may not have the appropriate access-control-origin settings.

### ISSUE THREAD

**Issue by tagantroy** [iheartradio/play-swagger#24]
I did everything according guide,but i got this error when i try to use swagger(docker container) + my api(docker container)
i didn't find any information about this problem in your guide

**Comment by kailuowang** [comment]
This is due to the fact that you are trying to have your swagger access the json from another domain (your play app on the other container). 
you can either enable CORS in your play app: https://www.playframework.com/documentation/2.4.x/CorsFilter 
and swagger UI
https://github.com/swagger-api/swagger-ui/blob/master/README.md#cors-support
 or you can setup a proxy (e.g. nginx or haproxy or apache) in your swagger ui host which points to the play api. 

This is not a play-swagger library issue. If you don't mind I am going to close this issue.
