### ISSUE TITLE
Play-Swagger integrations

### ISSUE THREAD

**Issue by benmccann** [iheartradio/play-swagger#32]
Awesome to see a Play-Swagger integration. It's something I'm really interested in at the moment and I've been trying to figure out the best way to do it.

I just added your project on the [swagger-api/swagger-play](https://github.com/swagger-api/swagger-play) README, so that others can find your project. We've been [working on fixing up swagger-api/swagger-play](https://github.com/swagger-api/swagger-play/pull/23) so that it runs with Swagger 2.0 and Play 2.4, but I wasn't aware of your effort.

A few thoughts I had...

* We do routes file parsing in [our PR](https://github.com/swagger-api/swagger-play/pull/23). We just copied the Play routes parser into our code, but the Play guys created a PR to make it into a library we can use. Thought you'd be interested: https://github.com/playframework/playframework/pull/5291
* Is there a reason you chose adding comments to the routes file instead of generating the routes from the Swagger spec? [There's another project that has code for that](https://github.com/zalando/play-swagger). I'm thinking that might make it easy to run the spec though a validator if it's a stand-alone spec vs mixed in the routes syntax. Thinking about different possible approaches here...
* Does this only work with Scala case classes? I use Java and I'm wondering if it'll work with POJOs

Thanks for open sourcing this guys!

**Comment by kailuowang** [comment]
@benmccann thank you for adding to the swagger-play readme. It is a nice thing for users of swagger and play to have multiple alternatives. 


1, Thanks for letting us know about the routes parser PR, we can definitely use that.  
2, Personally I like play's routes DSL and our developers are more familiar to it than swagger spec.  
IMHO play routes DSL is more concise than the swagger spec equivalent when providing the basic information, e.g.
`controllers.GN.createCard(profileId: Int, contextName: String)`  v.s.
```
parameters: [
  { name: "profileId",
    type: "integer",
    format: "int32",
    required: true
  },
  { name: "contextName",
    type: "string",
    required: true
  }
]
```
So that's less work for adding swagger to an existing play app, especially when you don't need to add a bunch of extra information than what the routes files already provide.  In most cases all they need to add is a description and a respond and/or a request body ref. 

I'm also a little concern over the number of layers of code generation in that approach, a swagger spec generating routes file than generate java routes classes. Could be hard to debug. 
3, this library uses runtime reflection to the get the arguments list of the main constructor. I am certain it won't work with POJOs that lack a constructor with all fields. Not sure the other case. (sorry my java is even weaker than my scala), but I don't think it will be too hard to enhance it to work with POJOs.
