### ISSUE TITLE
Swagger-ui compatibility

### ISSUE THREAD

**Issue by jessebutterfield** [iheartradio/play-swagger#457]
Swagger UI has by default turned off controlling the default url with query parameters (see https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx). So any version of swagger-ui > 4.1.2 using the setup in 3b will default to showing swagger's example pet store instead of your local swagger definitions.

**Comment by Javakky-pxv** [comment]
@jessebutterfield 
I had the same problem.
I copied `index.html` and `swagger-initializer.js` locally and rewrote `SwaggerUIBundle#url`.
Do you know of any other countermeasures?

**Comment by Javakky-pxv** [comment]
@jessebutterfield
The above has been added to the `README`.

**Comment by DraganRaicici** [comment]
Hi there. 

I'm not sure I understand what you guys mean by "I copied index.html and swagger-initializer.js locally"...
Do you mean we should create a new route that points to that newly copied `index.html`file with the modified `swagger-initializer.js`?

If so, I also have to copy over the `swagger-ui-bundle.js`, `swagger-ui-standalone-preset.js` files, the favicons and the `swagger-ui.css` file as well.

I must be misunderstanding the solution since this seems a little over the top.

Also, if I may, can you please review the `README`?
This sentence does not make sense:
"Copy the index.html and swagger-initializer.js generated in target/${project}/public/lib/main/swagger-ui/ and modify the js files as follows to create Swagger-UI can be used easily."

More specifically: "...modify the js files as follows to craete Swagger-UI can be used easily."

For more information: my project is a REST api with no views and it's running on Scala version 2.13.10, Play version 2.8.19 and sbt-play-swagger version 1.0.0
