### ISSUE TITLE
$ref: Type is not defined

### ISSUE THREAD

**Issue by vasily-kirichenko** [iheartradio/play-swagger#91]
I'm struggling to understand what a proper path should be for the following `File` type:

Project structure

![image](https://cloud.githubusercontent.com/assets/873919/17171650/4ae5bdfe-53fa-11e6-99db-9e645244f568.png)

routes
```
###
#  summary: get files by FC hash
#  responses:
#    200:
#      description: success
#      schema:
#        $ref: '#/definitions/models.File'
###
GET /get/:hash                controllers.HashStore.getFiles(hash: Long)
```

Error

![image](https://cloud.githubusercontent.com/assets/873919/17171699/7cb5b46a-53fa-11e6-9745-372655533d9f.png)

**Comment by kailuowang** [comment]
I am wondering if you included the `models` package as a domain package name when generating the swagger spec as in https://github.com/iheartradio/play-swagger#step-2?

**Comment by vasily-kirichenko** [comment]
I didn't. Thanks a lot! 

Maybe it's a good idea to add a hint like "are you sure you added 'xxx' package as a domain one?"

**Comment by AngelosPrastitis** [comment]
I agree with Vasily. I spent two days trying to see the model in Swagger UI because I didn't add the domain package that i should. Some people have restricted knowledge of the terms (in my case i didn't understand the term domain package). Therefore in step1 of the instructions where we are instructed to put swaggerDomainNameSpaces := Seq("models") in the sbt file I I put it exactly identical to the instruction. My defined model case class was in the domain settings.models in my project.

It would be nice to add the following in this instruction:
If you have a case class defined under the package "something.models" and you would want to swagger to generate the definition for it (to access with #ref:definitions/), then make sure that the following is added in sbt: swaggerDomainNameSpaces := Seq("something.models") 
If you have other case classes in other packages (e.g. other.models) the add them also in the above sequence like: swaggerDomainNameSpaces := Seq("something.models","other.models")

**Comment by kailuowang** [comment]
@AngelosPrastitis thanks for your feedback. Would you help by submitting a PR to the readme file?
